networks:
    dev:

volumes:
    mongo_data:

services:
    nginx:
        image: nginx:stable-alpine
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - './nginx.conf:/etc/nginx/nginx.conf'
            - '/etc/letsencrypt:/etc/letsencrypt'
        depends_on:
            - backend
            - frontend
        networks:
            - dev

    backend:
        build:
            context: ./backend
        environment:
            MONGODB_CONNECTION_STRING: 'mongodb://user:mongopass@mongo:27017/tasky?authSource=admin'
        depends_on:
            - mongo
        networks:
            - dev

    frontend:
        build:
            context: ./frontend
        networks:
            - dev
    mongo:
        image: mongo:latest
        container_name: mongo
        restart: always
        environment:
            MONGO_INITDB_DATABASE: tasky
            MONGO_INITDB_ROOT_USERNAME: user
            MONGO_INITDB_ROOT_PASSWORD: mongopass
        volumes:
            - mongo_data:/data/db
        ports:
            - '27017:27017'
        networks:
            - dev
