export enum ACTION_TYPE {
	LOGOUT = 'LOGOUT',
	SET_USER = 'SET_USER',

	SET_PROJECTS = 'SET_PROJECTS',
	ADD_PROJECT = 'ADD_PROJECT',
	UPDATE_PROJECT = 'UPDATE_PROJECT',
	REMOVE_PROJECT = 'REMOVE_PROJECT',

	OPEN_MODAL = 'OPEN_MODAL',
	CLOSE_MODAL = 'CLOSE_MODAL',
	SET_SEARCH_PHRASE = 'SET_SEARCH_PHRASE',

	START_TIMER = 'START_TIMER',
	UPDATE_TIMER = 'UPDATE_TIMER',
	STOP_TIMER = 'STOP_TIMER',
	PAUSE_TIMER = 'PAUSE_TIMER',
	RESUME_TIMER = 'RESUME_TIMER',
	LOAD_SAVED_TIMER = 'LOAD_SAVED_TIMER',

	RESET_FILTERS = 'RESET_FILTERS',
	SET_STATUS_FILTER = 'SET_STATUS_FILTER',
	SET_ESTIMATION_FILTER = 'SET_ESTIMATION_FILTER',
}
